export const pytania = {
	questions: [
		{
			id: 1,
			question: "Jaki jest jej ulubiony kolor?",
			answers: ["niebieski", "fioletowy", "rożowy", "pomarańczowy"],
			correctAnswer: "rożowy",
			video: "/pucia-i-jogurcik/p1.mp4",
			answerVideo: "/pucia-i-jogurcik/o1.mp4",
		},
		{
			question: "Jaki jest jej kolor oczu?",
			id: 2,
			answers: [
				"brązowe",
				"piwne",
				"yyy... o kurka... nie wiem",
				"oczywiście, że różowe",
			],
			correctAnswer: "brązowe",
			video: "/pucia-i-jogurcik/p2.mp4",
			answerVideo: "/pucia-i-jogurcik/o2.mp4",
		},
		{
			question: "Co woli: wódkę, wino czy piwo?",
			id: 3,
			answers: ["wódkę", "wino", "piwo"],
			correctAnswer: "piwo",
			video: "/pucia-i-jogurcik/p3.mp4",
			answerVideo: "/pucia-i-jogurcik/o3.mp4",
		},
		{
			question: "Woli wypad w góry, nad morze czy nad jezioro?",
			id: 4,
			answers: ["góry", "morze", "jezioro"],
			correctAnswer: "góry",
			video: "/pucia-i-jogurcik/p4.mp4",
			answerVideo: "/pucia-i-jogurcik/o4.mp4",
		},
		{
			question: "Jaki jest jej ulubiony film?",
			id: 5,
			answers: [
				"ten taki no ten, Koreański",
				"Pamiętnik",
				"o kurcze, nie wiem",
				"Kraina Lodu",
			],
			correctAnswer: "Pamiętnik",
			video: "/pucia-i-jogurcik/p5.mp4",
			answerVideo: "/pucia-i-jogurcik/o5.mp4",
		},
		{
			question: "Jaka jest Twoja ulubiona piosenka?",
			id: 6,
			answers: [
				"London Symphony Orchestra - The Imperial March",
				"Linkin Park - Numb",
				"Happy Sad - Ja do Ciebie",
				"Linkin Park - Somewhere I Belong",
			],
			correctAnswer: "Linkin Park - Somewhere I Belong",
			video: "/pucia-i-jogurcik/p6.mp4",
			answerVideo: "/pucia-i-jogurcik/o6.mp4",
		},
		{
			question: "Co najbardziej cenisz w Nati?",
			id: 7,
			answers: [
				"hehe.. no wiesz co",
				"jej podejście do ludzi",
				"pucie",
				"jej inteligencje",
			],
			correctAnswer: "jej podejście do ludzi",
			video: "/pucia-i-jogurcik/p7.mp4",
			answerVideo: "/pucia-i-jogurcik/o7.mp4",
		},
		{
			question: "Woli spać od ściany czy od zewnątrz?",
			id: 8,
			answers: ["ściany", "zewnątrz"],
			correctAnswer: "ściany",
			video: "/pucia-i-jogurcik/p8.mp4",
			answerVideo: "/pucia-i-jogurcik/o8.mp4",
		},
		{
			question: "Śpi na brzuchu, na plecach czy na boku?",
			id: 9,
			answers: ["brzuchu", "bokubrzuchu", "plecach", "boku"],
			correctAnswer: "bokubrzuchu",
			video: "/pucia-i-jogurcik/p9.mp4",
			answerVideo: "/pucia-i-jogurcik/o9.mp4",
		},
		{
			question: "Gdzie odbyła się Wasza pierwsza randka?",
			id: 10,
			answers: [
				"Obiad w Greco",
				"Koncert (koniec świata)",
				"Piwo/drink pod nasypem",
				"wieża widokowa Kotowice",
			],
			correctAnswer: "wieża widokowa Kotowice",
			video: "/pucia-i-jogurcik/p10.mp4",
			answerVideo: "/pucia-i-jogurcik/o10.mp4",
		},
		{
			question: "Jaka jest Wasza ulubiona piosenka?",
			id: 11,
			answers: [
				"Happy Sad - Zanim pójdę",
				"Koniec Świata - Oranżada",
				"Happy Sad - Ja do Ciebie",
				"Strachy na Lachy - Dzień dobry, kocham Cię",
			],
			correctAnswer: "Happy Sad - Zanim pójdę",
			video: "/pucia-i-jogurcik/p11.mp4",
			answerVideo: "/pucia-i-jogurcik/o11.mp4",
		},
		{
			question: "Kto z Was jest bardziej kłótliwy?",
			id: 13,
			answers: [
				"ja",
				"Natalia",
				"nie wiem czy chcę odpowiadać na to pytanie",
				"obydwoje",
			],
			correctAnswer: "Natalia",
			video: "/pucia-i-jogurcik/p12.mp4",
			answerVideo: "/pucia-i-jogurcik/o12.mp4",
		},
		{
			question: "Kto częściej ustępuje?",
			id: 13,
			answers: ["ja", "Naja", "obydwoje"],
			correctAnswer: "ja",
			video: "/pucia-i-jogurcik/p13.mp4",
			answerVideo: "/pucia-i-jogurcik/o13.mp4",
		},
		{
			question: "Ile chcielibyście mieć dzieci?",
			id: 14,
			answers: ["1", "2", "3", "Ile się da"],
			correctAnswer: "2",
			video: "/pucia-i-jogurcik/p14.mp4",
			answerVideo: "/pucia-i-jogurcik/o14.mp4",
		},
		{
			question: "Kto będzie wasze dzieci uczył śpiewać, a kto liczyć?",
			id: 15,
			answers: [
				"ja liczyć, Natalia śpewać",
				"ja śpiewać, Natalia liczyć",
			],
			correctAnswer: "ja śpiewać, Natalia liczyć",
			video: "/pucia-i-jogurcik/p15.mp4",
			answerVideo: "/pucia-i-jogurcik/o15.mp4",
		},
		{
			question: "Kto się częściej śmieje?",
			id: 16,
			answers: ["ja", "Natalia", "obydwoje"],
			correctAnswer: "ja",
			video: "/pucia-i-jogurcik/p16.mp4",
			answerVideo: "/pucia-i-jogurcik/o16.mp4",
		},
		{
			question: "Jaki ma rozmiar miseczki?",
			id: 17,
			answers: ["nie wiem", "C", "B", "D"],
			correctAnswer: "C",
			video: "/pucia-i-jogurcik/p17.mp4",
			answerVideo: "/pucia-i-jogurcik/o17.mp4",
		},
	],
};
