import { Emilys_Candy } from "next/font/google";
import "./globals.css";

const emilysCandy = Emilys_Candy({
	variable: "--font-emily-candy",
	weight: "400",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${emilysCandy.className}`}>{children}</body>
		</html>
	);
}
